/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcd_prak1;
import pcd_prak1.classapp;
import javax.swing.JFileChooser;

/**
 *
 * @author whoami
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public classapp pcd_prak1;
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnfile = new javax.swing.JMenu();
        miopen = new javax.swing.JMenuItem();
        misave = new javax.swing.JMenuItem();
        miexit = new javax.swing.JMenuItem();
        mnedit = new javax.swing.JMenu();
        migrayscale = new javax.swing.JMenuItem();
        mibiner = new javax.swing.JMenuItem();
        mibrightness = new javax.swing.JMenuItem();
        midefault = new javax.swing.JMenuItem();
        mnop = new javax.swing.JMenu();
        mizoomin = new javax.swing.JMenuItem();
        mizoomout = new javax.swing.JMenuItem();
        mivertikal = new javax.swing.JMenuItem();
        mihorizontal = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mirotation90 = new javax.swing.JMenuItem();
        mirotation180 = new javax.swing.JMenuItem();
        mirotation270 = new javax.swing.JMenuItem();
        mirotation360 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        mnfile.setText("File");

        miopen.setText("Open");
        miopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miopenActionPerformed(evt);
            }
        });
        mnfile.add(miopen);

        misave.setText("Save");
        misave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misaveActionPerformed(evt);
            }
        });
        mnfile.add(misave);

        miexit.setText("Exit");
        miexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miexitActionPerformed(evt);
            }
        });
        mnfile.add(miexit);

        jMenuBar1.add(mnfile);

        mnedit.setText("Edit");

        migrayscale.setText("Grayscale");
        migrayscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                migrayscaleActionPerformed(evt);
            }
        });
        mnedit.add(migrayscale);

        mibiner.setText("Biner");
        mibiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibinerActionPerformed(evt);
            }
        });
        mnedit.add(mibiner);

        mibrightness.setText("Brightness");
        mibrightness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibrightnessActionPerformed(evt);
            }
        });
        mnedit.add(mibrightness);

        midefault.setText("Default");
        midefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midefaultActionPerformed(evt);
            }
        });
        mnedit.add(midefault);

        jMenuBar1.add(mnedit);

        mnop.setText("Op.Geometri");

        mizoomin.setText("Zoom in");
        mizoomin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mizoominActionPerformed(evt);
            }
        });
        mnop.add(mizoomin);

        mizoomout.setText("Zoom out");
        mizoomout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mizoomoutActionPerformed(evt);
            }
        });
        mnop.add(mizoomout);

        mivertikal.setText("Flip Vertikal");
        mivertikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivertikalActionPerformed(evt);
            }
        });
        mnop.add(mivertikal);

        mihorizontal.setText("Flip Horizontal");
        mihorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mihorizontalActionPerformed(evt);
            }
        });
        mnop.add(mihorizontal);

        jMenuBar1.add(mnop);

        jMenu1.setText("Rotation");

        mirotation90.setText("Rotation (90)");
        mirotation90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirotation90ActionPerformed(evt);
            }
        });
        jMenu1.add(mirotation90);

        mirotation180.setText("Rotation (180)");
        mirotation180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirotation180ActionPerformed(evt);
            }
        });
        jMenu1.add(mirotation180);

        mirotation270.setText("Rotation (270)");
        mirotation270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirotation270ActionPerformed(evt);
            }
        });
        jMenu1.add(mirotation270);

        mirotation360.setText("Rotation (360)");
        mirotation360.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirotation360ActionPerformed(evt);
            }
        });
        jMenu1.add(mirotation360);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void misaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misaveActionPerformed
        // TODO add your handling code here:
        JFileChooser TDialog = new JFileChooser();
        if(TDialog.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            pcd_prak1.SaveImage(TDialog.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_misaveActionPerformed

    private void miopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miopenActionPerformed
        // TODO add your handling code here:
        JFileChooser TDialog = new JFileChooser();
        if(TDialog.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
            pcd_prak1= new classapp(TDialog.getSelectedFile().getAbsolutePath(),355,355);
            jLabel1.setIcon(pcd_prak1.GetIcon());
        }
    }//GEN-LAST:event_miopenActionPerformed

    private void miexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_miexitActionPerformed

    private void migrayscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_migrayscaleActionPerformed
        // TODO add your handling code here:
        pcd_prak1.Grayscale();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_migrayscaleActionPerformed

    private void mibinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibinerActionPerformed
        // TODO add your handling code here:
        pcd_prak1.Biner();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mibinerActionPerformed

    private void midefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midefaultActionPerformed
        // TODO add your handling code here:
        pcd_prak1.Default();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_midefaultActionPerformed

    private void mibrightnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibrightnessActionPerformed
        // TODO add your handling code here:
        pcd_prak1.Brightness();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mibrightnessActionPerformed

    private void mihorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mihorizontalActionPerformed
        // TODO add your handling code here:
        pcd_prak1.fliphorizontal();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mihorizontalActionPerformed

    private void mivertikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivertikalActionPerformed
        // TODO add your handling code here:
        pcd_prak1.flipvertikal();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mivertikalActionPerformed

    private void mizoominActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mizoominActionPerformed
        // TODO add your handling code here:
        pcd_prak1.zoomin();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mizoominActionPerformed

    private void mizoomoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mizoomoutActionPerformed
        // TODO add your handling code here:
        pcd_prak1.zoomout();
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mizoomoutActionPerformed

    private void mirotation90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirotation90ActionPerformed
        // TODO add your handling code here:
        pcd_prak1.rotation(90, this);
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mirotation90ActionPerformed

    private void mirotation180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirotation180ActionPerformed
        // TODO add your handling code here:
        pcd_prak1.rotation(180, this);
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mirotation180ActionPerformed

    private void mirotation270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirotation270ActionPerformed
        // TODO add your handling code here:
        pcd_prak1.rotation(270, this);
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mirotation270ActionPerformed

    private void mirotation360ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirotation360ActionPerformed
        // TODO add your handling code here:
        pcd_prak1.rotation(360, this);
        jLabel1.setIcon(pcd_prak1.ScaleResultIcon);
    }//GEN-LAST:event_mirotation360ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mibiner;
    private javax.swing.JMenuItem mibrightness;
    private javax.swing.JMenuItem midefault;
    private javax.swing.JMenuItem miexit;
    private javax.swing.JMenuItem migrayscale;
    private javax.swing.JMenuItem mihorizontal;
    private javax.swing.JMenuItem miopen;
    private javax.swing.JMenuItem mirotation180;
    private javax.swing.JMenuItem mirotation270;
    private javax.swing.JMenuItem mirotation360;
    private javax.swing.JMenuItem mirotation90;
    private javax.swing.JMenuItem misave;
    private javax.swing.JMenuItem mivertikal;
    private javax.swing.JMenuItem mizoomin;
    private javax.swing.JMenuItem mizoomout;
    private javax.swing.JMenu mnedit;
    private javax.swing.JMenu mnfile;
    private javax.swing.JMenu mnop;
    // End of variables declaration//GEN-END:variables
}
